social media post:
  is_a: named thing
  represented_as: node
  input_label: social_media_post
  properties:
    text: str
    platform: str
    country: str
    timestamp: str
    retweets: int
    likes: int
    source_row_ids: str[]
    source_legacy_indices: str[]

user:
  is_a: named thing
  represented_as: node
  input_label: user
  properties:
    display_name: str

hashtag:
  is_a: named thing
  represented_as: node
  input_label: hashtag
  properties:
    name: str

emotion:
  is_a: named thing
  represented_as: node
  input_label: emotion
  properties:
    name: str

posted:
  is_a: association
  represented_as: edge
  input_label: posted
  source: user
  target: social media post

has tag:
  is_a: association
  represented_as: edge
  input_label: has_tag
  source: social media post
  target: hashtag

expresses:
  is_a: association
  represented_as: edge
  input_label: expresses
  source: social media post
  target: emotion
